### ISSUE TITLE
primitive-0.8 not accepted

### ISSUE THREAD

**Issue by ysangkok** [cchalmers/pcg-random#11]
This is one of the last packages not compatible: https://github.com/commercialhaskell/stackage/issues/6887

The package will have to be removed from Stackage if Stackage were to upgrade.

This package is important, because it is a dependency of random-bytestring, which is required by packages like base16, base64.

**Comment by cchalmers** [comment]
Thanks for the report. I've bumped the primitive bounds. I'm also using the new `genWord64` function instead of `next` and bumped the random lower bound. I've published v0.1.4.0: https://hackage.haskell.org/package/pcg-random-0.1.4.0.
