### ISSUE TITLE
Windows has no /dev/urandom, always gets warning message

### ISSUE THREAD

**Issue by tejon** [cchalmers/pcg-random#2]
There is no built-in way to suppress the warning about inferior clock seeding. It can get awfully spammy while testing things!

**Comment by cchalmers** [comment]
Fixed with cd7d1122ea06bcab15778dae83284062fb0a79e6. It now uses [entropy](https://hackage.haskell.org/package/entropy) which uses CryptAPI for Windows.

**Comment by tejon** [comment]
Woah... that was fast! :D
