### ISSUE TITLE
Consider dropping the "better-than-typical cryptographic security" blurb

### ISSUE THREAD

**Issue by ivarnymoen** [cchalmers/pcg-random#4]
Perhaps it's just me, but I read this statement as "better than your average cryptographically secure prng".

While PCG is less predictable than many other PRNGs, it's not a CSPRNG.

**Comment by cchalmers** [comment]
Indeed. I just quoted http://www.pcg-random.org but it looks like it's been changed (probably for similar reasons to yours). I'll change it to what it says now:

> PCG is a family of simple fast space-efficient statistically good algorithms for random number generation. Unlike many general-purpose RNGs, they are also hard to predict.
